export { default as LogoIcon } from './LogoSvg'
export { default as WhatsAppIcon } from './WhatAppSvg'
export { default as AppleIcon } from './AppleSvg'
export { default as GoogleIcon } from './GoogleSvg'
export { default as MenuIcon } from './MenuSvg'
